name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install
        run: yarn install

      - name: build
        run: yarn run build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'

      - name: create .nojekyll
        run: touch .output/public/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
           path: '.output/'


  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4